Removed machineSettings
Error: Code=InvalidTemplate; Message=Deployment template validation
failed: 'The template parameters 'machineSettings' in the parameters
file are not valid; they are not present in the original template and
can therefore not be provided at deployment time. The only supported
parameters for this template are 'globals, dnsServers, adminPassword,
sicKey'.